
== Music

=== 1. You indicated in the survey that you like listening to music. Can you tell me what kind of music you like? And who is your favorite musician?Why do you like him or her?

I like to listen to a various kind of music. what i'm listening to depends on my feelings.
In these days I like to listen to ballad music because I've heard that my favorite singer prepare the concert. That kind of music make me feel touched and feel relaxed. Also it always blows my mind.

As for my favorite singer, I'm gonna talk about 이승환 who is one of the most famous male singer in Korean Pop. He debuted in the late 1980s. He has a big fans especially in my ages. Including me, they have spent their youth with his song. He has written and produced hundreds of song and albums. He still have hold serveral concert in every year.

His song and tones is so touching and catchy. After I listened a song in his 4th alumn called "천일동안" which mean 'love for 1000 days', I admired him. I even sang his song to my wife in my wedding. it is named in 'unfancy confession'. I chose the song because of the lyrics. The lyrics is about 'sincere and unchaged love without any condition.' I love that song.

Overall, that's my taste in music and favorie singer. Thank you.


=== 2. How did you first get interested in music? What kind of music did you listen to when you were young? How was that music different from the music you listen to today? How has your interest in music changed over the years?

When I was in a high school, i tried to learn a rap. In those days, the student went to singing room with friends for playing. I was not good at singing and I wanted to be standout in the singing room, so i tried to find something else. At that time,  Rapper called 김진표 was getting more famous. I decided to memorize all lyrics of his song in his album . After then, I was interete in rap music.

Several years ago, I had a chance to see a musical in my first time. It was sooooo good. and then I bought the album of the musical and listened every day. The musical was the Man of La Mancah which story is about Don Quixote. My favorite song is "Impossible Dream." It helped me overcoming emotinoal diffilculties in those days. Since then, I have listened the song to be braver or more confident when I'm in a trouble emotionally.

Sooo, This is about changes of my music taste.


=== 3. Tell me about a time when you went to listen to some live music. Perhaps it was at a concert or live café. What was the mood like?How did you like the music you listen to there?

There are many parks in 성남 city which I'm living in. In one of them, big concert hall located in the cetral park in 분당. the city held a concert of Old Korea Pop Singer several years ago.

The guest I can remember were POSITION, 박혜경 who were pop stars in 1990.
They sang servral their hit songs, people was getting exited in the concert.

The main guest was 김건모, he is still star in Korean TV Show. After he showed up, people standed up and sing along his songs as they were young. The mood of the concert gradually rose and he sang a couple of additional song then the show finished.

I and my wife really had time to recall our youth. this is about my recent expeirence for live music.

== Travel
Intensive_Travel

=== 1. You indicated in the survey that you take vacations domestically. Tell me some places you like to travel. Why do you like to go there?

My favorite place in Korean is Jeju Island which is localed south of the Korean Peninsula. There are one of the most famous places for Korean because climate is mild and warm even in the winter seaons.

First of all, nature in the island is well maintained and beautiful. There are a lot of forest around the island. You can get relaxed with fresh air if you get into forest except in the winter season.

Plus you can see the tallest mountain in South Korea, which is called 한라 Mountian. You can see the mountain wherever you are if the weather is find. in the winter season, you can see the snows on the top of mountain.

And it is good place for travelers in the terms of cost. In the case of rent car. there are so many rent car companies around Jeju Internaltional airport. As you know, compantition make customers happy. The rent price is quite cheap, maybe it's not over $20 a day with full coverage insurance for regular car for 4 person. So you can go easily wherever you want to go in low cost. I rent for whole days in the previous trip.

Overall, there are other reasons why people like that island. there is no enough time to explain.

=== 2. Let’s say you are preparing to take a trip somewhere. Tell me about all the things that you usually do to get ready.

Well. I'm a person who like to prepare somehting to be scheduled.

The first thing I shuold do is to buy or reserve a tocket for transportation. if i cant' get a ticket, there is no alternatives.

the second one I usually do is to booking a hotel. I think accomodation during a trip is quite important for trip's satisfaction. So, If I have a enough money, I spend much amount of money for a high-quality acocomodation. Easpecially for having a good pool and breakfast.

Final doing for a preparation is to list up the activities that I or my travenling party want to do with like fishing on the boat or take a massage.

Those things are what i prepare to travel mainly. Thank you for listening.


=== 3. Think of a memorable trip you took when you were younger. Where did you go and who did you go with? What did you do or see during that trip?

I can remember the trip to Jeju Island with my whole family a couple of years ago. I have a trip with wife and daughter also with my paretns and brother's family. I stayed at the very special resort I'd never been for two days. It's very expensive resort, so i couldn't go there if I did't get benefits from a company. i guess it's over $1000 for one day.

There was a private building with 2 stories. After I got into the building, all things in the house were luxurious. We bought fresh seafood from local market and cooked and enjoy the dinner with wine and beer. We'd talked much during night. I think it is the most luxuirous trip in my life with whole family togeter.

I guess my parents were busy and they didn't have a chance to visit those kind of place. So I was very happy that whole family could be satisfied.
